"""add_processed_field

Revision ID: f808275e92ac
Revises: 291888c93aa4
Create Date: 2023-02-27 10:59:18.080424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f808275e92ac'
down_revision = '291888c93aa4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('hash', sa.Text(), nullable=False))
    op.add_column('uploaded_files', sa.Column('processed', sa.Boolean(), nullable=True))
    op.alter_column('uploaded_files', 'filename',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.drop_constraint('uploaded_files_filename_key', 'uploaded_files', type_='unique')
    op.drop_column('uploaded_files', 'checksum')
    op.drop_column('uploaded_files', 'last_modified')
    op.drop_column('uploaded_files', 'created_at')
    op.drop_column('uploaded_files', 'file_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_files', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('uploaded_files', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('uploaded_files', sa.Column('last_modified', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('uploaded_files', sa.Column('checksum', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_unique_constraint('uploaded_files_filename_key', 'uploaded_files', ['filename'])
    op.alter_column('uploaded_files', 'filename',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('uploaded_files', 'processed')
    op.drop_column('uploaded_files', 'hash')
    # ### end Alembic commands ###
